version: '3.8'

services:
  app:
    container_name: nestjs_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=nestdb

  db:
    container_name: postgres_db
    image: postgres:13
    environment:
      POSTGRES_USER: pgql
      POSTGRES_PASSWORD: pgql
      POSTGRES_DB: nestdb
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data